function createBalloonContentLayout() {
    window.MyBalloonContentLayout = ymaps.templateLayoutFactory.createClass(
        ['<a class="hideRobots" data-id="$[properties.id]" href="#" rel="/krasnodar/$[properties.slug]"><h2>$[properties.name]</h2></a>',
            '<div class="image">',
            '<img src="$[properties.image]" alt="">',
            '</div>',
            '<div class="term">',
            '<span class="icon icon-calendar"></span><p>Срок сдачи<br>$[properties.deadline]</p>',
            '</div>',
            '<div class="parameters">',
            '<table>',
            '<tr>',
            '<th class="count">Кол-во<br>комнат</th>',
            '<th class="area">Площадь<br>м2 от&mdash;до</th>',
            '<th class="price">Цена<br>млн Р от&mdash;до</th>',
            '</tr>',
            '<tr>',
            '<td>Студия</td>',
            '<td>$[properties.areas1.min]&mdash;$[properties.areas1.max]</td>',
            '<td>$[properties.prices1.min]&mdash;$[properties.prices1.max]</td>',
            '</tr>',
            '<tr>',
            '<td>1</td>',
            '<td>$[properties.areas2.min]&mdash;$[properties.areas2.max]</td>',
            '<td>$[properties.prices2.min]&mdash;$[properties.prices2.max]</td>',
            '</tr>',
            '<tr>',
            '<td>2</td>',
            '<td>$[properties.areas3.min]&mdash;$[properties.areas3.max]</td>',
            '<td>$[properties.prices3.min]&mdash;$[properties.prices3.max]</td>',
            '</tr>',
            '<tr>',
            '<td>3</td>',
            '<td>$[properties.areas4.min]&mdash;$[properties.areas4.max]</td>',
            '<td>$[properties.prices4.min]&mdash;$[properties.prices4.max]</td>',
            '</tr>',
            '<tr>',
            '<td>4+</td>',
            '<td>$[properties.areas5.min]&mdash;$[properties.areas5.max]</td>',
            '<td>$[properties.prices5.min]&mdash;$[properties.prices5.max]</td>',
            '</tr>',
            '</table>',
            '</div>',
            '</div>'].join('')
    );

}